ARG RUBY_VERSION=3.4.4
FROM docker.io/library/ruby:$RUBY_VERSION-slim

# Rails app lives here
WORKDIR /workspace

# Install base packages and Docker CLI dependencies
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    curl \
    libjemalloc2 \
    libclang1 \
    clang \
    libyaml-dev \
    ca-certificates \
    gnupg \
    lsb-release \
    openssl \
    openssh-client \
    git && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# Install packages needed to build gems
RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    build-essential \
    git \
    pkg-config && \
    rm -rf /var/lib/apt/lists/* /var/cache/apt/archives

# Install Node.js and Yarn
RUN curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    npm install --global yarn && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Install Rails
RUN gem install rails -v 8

# Install Claude
RUN npm install -g @anthropic-ai/claude-code

EXPOSE 3000
